# Generated by Django 4.2.1 on 2023-06-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplinit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mplinit',
            name='expr',
            field=models.CharField(max_length=150),
        ),
    ]
