# Generated by Django 4.2.1 on 2023-06-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplinit', '0002_alter_mplinit_expr'),
    ]

    operations = [
        migrations.CreateModel(
            name='TNN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expr', models.CharField(max_length=150)),
                ('x_value', models.CharField(max_length=50)),
            ],
        ),
    ]
